// Generated by https://quicktype.io

export interface LoginData {
    email: string;
    password: string;
}

export interface RegisterData {
    name: string;
    email: string;
    password: string;
}

export interface LoginResponse {
    user:  User;
    token: string;
}

export interface User {
    uid:  string;
    name: string;
}

