// Generated by https://quicktype.io

export interface ReviewsResponse {
    ok:      boolean;
    reviews: Review[];
}

export interface Review {
    title:         string;
    description:   string;
    qualification: string;
    user:          User;
    id:            string;
    username?:     string;
}

export interface User {
    _id:  string;
    name: string;
}

// Generated by https://quicktype.io

export interface AddResponse {
    ok:          boolean;
    reviewSaved: ReviewSaved;
}

export interface ReviewSaved {
    title:         string;
    description:   string;
    qualification: string;
    user:          string;
    id:            string;
}


